bookspot/config/routes.rb
Rails.application.routes.draw do
  get 'search', to: "search#index"
  get 'orders/success'
  get 'orders/bought'
  get 'orders/sold'
  get 'help', to: "pages#help", as: "help"
  get 'help/guide', to: "pages#guide", as: "guide"
  get 'help/sitemap', to: "pages#sitemap", as: "sitemap"
  resources :listings
  devise_for :accounts
  root 'pages#home'

  post "listings/:id/order", to: "listings#place_order", as: "place_order"

  get "orders/success"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

bookspot/app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # Note: only default devise modules used for this application
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # A user will only need to create a single account
  # With this single account, the user can have zero to many listings, bought orders and sold orders
  has_many :listings
  has_many :sold_orders, foreign_key: "seller_id", class_name: "Order"
  has_many :bought_orders, foreign_key: "buyer_id", class_name: "Order"
end

bookspot/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookspot/app/models/category.rb
class Category < ApplicationRecord
end

bookspot/app/models/listing.rb
class Listing < ApplicationRecord
  # Only an authenticated user can create listings - therefore listings belong to one and only one account
  belongs_to :account
  belongs_to :category
  # Fields within the listing required more than just a selection or plain text

  has_rich_text :description
  has_one_attached :picture

  # Conditions associated with numeric value for better user experience
  enum condition: {
    tattered_and_worn: 1,
    very_loved: 2, 
    a_little_loved: 3, 
    new_and_shiny: 4
  }
end

bookspot/app/models/order.rb
class Order < ApplicationRecord
  # Only an authenticated user can make an order and an order can only occur when there is a listing to purchase
  # Therefore, and order belongs to a listing, a buyer and a seller 
  belongs_to :listing
  belongs_to :buyer, foreign_key: "buyer_id", class_name: "Account"
  belongs_to :seller, foreign_key: "seller_id", class_name: "Account"
end

bookspot/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Devise gem primarily operates through the below before_action
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :set_query

    
    def set_query
        @query = Listing.ransack(params[:q])
    end

    protected

    # Method for setting devise santizisation 
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

bookspot/app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy place_order ]
  before_action :set_form_vars, only: %i[ new edit ]
  # Create before_actions to determine authentication and authorisation of the user
  # Only authenticated users can create, edit or destroy their own listings
  # Purchasing of said listings is handled by the Orders Controller
  before_action :authenticate_account!, except: [:index, :show]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  #CRUD operations for listings managed by methods below
  # GET /listings or /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1 or /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.account = current_account

    respond_to do |format|
      if @listing.save
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # Define a method for placing an order, which creates the order object with the listing_id, buyer_id and seller_id
  # Will also update sold status to prevent item being sold again (secondhand marketplace = unique items)
  # Will also redirect to success path to show success view
  def place_order
    Order.create(
      listing_id: @listing.id,
      seller_id: @listing.account_id, 
      buyer_id: current_account.id
    )

    @listing.update(sold: true)

    redirect_to orders_success_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    def set_form_vars
      @categories = Category.all
      @conditions = Listing.conditions.keys
    end

    def authorize_user
      if @listing.account_id != current_account.id
        flash[:alert] = "Not Authorised To Make Changes"
        redirect_to listings_path
      end
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:title, :author, :description, :condition, :price, :sold, :account_id, :category_id, :picture)
    end
end

bookspot/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # Define before_action to ensure only authenticated users can purchase items
  before_action :authenticate_account!

  # Method to help redirect to success page view once order is successful
  def success
  end

  # Methods to show authenticated user their own bought and sold items (zero or many)
  def bought
    @bought_items = current_account.bought_orders
  end

  def sold
    @sold_items = current_account.sold_orders
  end
end

bookspot/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # Use simple methods that correspond with the Views
  # The home page is used as the view through which all other functions can be accessed
  # and performed by their corresponding controllers
  def home
  end

  # Separate pages and methods created for the "help page" resources since 
  # these are displaying information that is hard coded in the view 
  def help
  end

  def guide
  end

  def sitemap
  end
end

bookspot/app/controllers/search_controller.rb
class SearchController < ApplicationController
  # Define method used by search to query database 
  # Ransack gem has been used 
  def index
    @query = Listing.ransack(params[:q])
    @listings = @query.result(distinct: true)
  end
end

bookspot/app/helpers/application_helper.rb
module ApplicationHelper
end

bookspot/app/helpers/listings_helper.rb
module ListingsHelper
    def format_condition(condition)
        words = condition.split("_").map do |word| 
            word.capitalize
        end
        words.join(" ")
    end

    def format_sold(sold)
        words = sold.map do |word|
            word.capitalize
        end
    end
end

bookspot/app/helpers/orders_helper.rb
module OrdersHelper
    def format_condition(condition)
        words = condition.split("_").map do |word| 
            word.capitalize
        end
        words.join(" ")
    end
end

bookspot/app/helpers/pages_helper.rb
module PagesHelper
end

bookspot/app/helpers/search_helper.rb
module SearchHelper
end

bookspot/app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

bookspot/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookspot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'shared/nav' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>


  <% if Rails.env.development? %>
    <% console %>
  <% end %>
  </body>
</html>

bookspot/app/views/listings/_form.html.erb
 <div class="container">
  <div class="row">

  <%= form_with(model: listing) do |form| %>
    <% if listing.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

        <ul>
          <% listing.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="u-full-width">
      <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title %>
      </div>

      <div class="field">
        <%= form.label :author %>
        <%= form.text_field :author %>
      </div>

      <div class="field">
        <%= form.label :description %>
        <%= form.rich_text_area :description %>
      </div>

      <div class="field">
        <% @conditions.each do |option| %>
        <%= form.label :condition, format_condition(option) %>
        <%= form.radio_button :condition, option %>
        <% end %>
      </div>

      <div class="field">
        <%= form.label :price %>
        <%= form.number_field :price %>
      </div>

      <div class="field">
        <%= form.label :category_id %>
        <%= form.select :category_id, @categories.map {|c| [c.name, c.id]} %>
      </div>

      <div class="field">
        <%= form.label :picture %>
        <%= form.file_field :picture, accept: "image/png,image/jpg,image/jpeg" %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    </div>
  <% end %>
</div>
</div>

bookspot/app/views/listings/edit.html.erb
 <div class="container">
  <div class="row">
    <h1>Editing Listing</h1>

    <%= render 'form', listing: @listing %>

    <%= link_to 'Show', @listing %> |
    <%= link_to 'Back', listings_path %>
  </div>
</div>

bookspot/app/views/listings/index.html.erb
<div class="container">
  <div class="row">
    <p id="notice"><%= notice %></p>

    <h1>Listings</h1>

    <table class="u-full-width">
      <thead>
        <tr>
          <th>Title</th>
          <th>Author</th>
          <th>Description</th>
          <th>Condition</th>
          <th>Price</th>
          <th>Sold</th>
          <th>Account</th>
          <th>Category</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @listings.each do |listing| %>
          <tr>
            <td><%= listing.title %></td>
            <td><%= listing.author %></td>
            <td><%= listing.description %></td>
            <td><%= format_condition(listing.condition) %></td>
            <td><%= number_to_currency(listing.price) %></td>
            <td><%= listing.sold %></td>
            <td><%= listing.account.username %></td>
            <td><%= listing.category.name %></td>
            <td><%= link_to 'Show', listing %></td>
            <% if current_account && current_account.id == listing.account_id %>
              <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
              <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Listing', new_listing_path %>
  </div>
</div>

bookspot/app/views/listings/new.html.erb
<div class="container">
  <div class="row">
    <h1>New Listing</h1>
 
    <%= render 'form', listing: @listing %>

    <%= link_to 'Back', listings_path %>
  </div>
</div>

bookspot/app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<div class="row">
  <div>
    <% if @listing.picture.attached? %>
      <%= image_tag @listing.picture, alt: @listing.title, height: 300, width: 250 %>
    <% else %>
      <%= image_tag "http://placekitten.com/200/300" , alt: @listing.title, height: 300, width: 250 %>
    <% end %>
  </div>

  <% if @listing.sold %>
    <p>NOT AVAILABLE TO PURCHASE</p>
  <% elsif current_account && current_account.id == @listing.account_id %>
    <p>CANNOT PURCHASE OWN ITEM</p>
  <% elsif current_account %>
    <%= button_to "Purchase", place_order_path%>
  <% elsif current_account == nil %>
    <p>PLEASE LOG IN OR MAKE AN ACCOUNT TO PURCHASE</p>
  <% end %>

  <p>
    <strong>Title:</strong>
    <%= @listing.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= @listing.author %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @listing.description %>
  </p>

  <p>
    <strong>Condition:</strong>
    <%= format_condition(@listing.condition) %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= number_to_currency(@listing.price) %>
  </p>

  <p>
    <strong>Account:</strong>
    <%= @listing.account.username %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= @listing.category.name %>
  </p>

  <% if current_account == @listing.account_id %>
    <%= link_to 'Edit', edit_listing_path(@listing) %> 
  <% else current_account == nil %>
    <%= link_to 'Show', listing_path(@listing) %>
  <% end %>
  <%= link_to 'Back', listings_path %>
</div>
</div>

bookspot/app/views/orders/bought.html.erb
<div class="container">
  <div class="row">

  <h1>Purchased Items</h1>
  <table class="u-full-width">
    <thead>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Description</th>
        <th>Condition</th>
        <th>Price</th>
        <th>Seller</th>
        <th>Category</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @bought_items.each do |item| %>
        <tr>
          <td><%= item.listing.title %></td>
          <td><%= item.listing.author %></td>
          <td><%= item.listing.description %></td>
          <td><%= format_condition(item.listing.condition) %></td>
          <td><%= number_to_currency(item.listing.price) %></td>
          <td><%= item.seller.username %></td>
          <td><%= item.listing.category.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

bookspot/app/views/orders/sold.html.erb
<div class="container">
  <div class="row">
    
  <h1>Sold Items</h1>


  <table class="u-full-width">
    <thead>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Description</th>
        <th>Condition</th>
        <th>Price</th>
        <th>Seller</th>
        <th>Category</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @sold_items.each do |item| %>
        <tr>
          <td><%= item.listing.title %></td>
          <td><%= item.listing.author %></td>
          <td><%= item.listing.description %></td>
          <td><%= format_condition(item.listing.condition) %></td>
          <td><%= number_to_currency(item.listing.price) %></td>
          <td><%= item.buyer.username %></td>
          <td><%= item.listing.category.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

bookspot/app/views/orders/success.html.erb
<h1>Thanks for your purchase!<h1>

bookspot/app/views/pages/guide.html.erb
<div class="container">
    <div class="row hero">
        <h1>Welcome to Bookspot Help</h1>
        <h4>Here is how to create an effective listing!</h4>
    </div>

    <div class="row">
        <ul="u-full-width">
            <li>Ensure you have no spelling errors in your title or author name, to ensure easy searching</li>
            <li>Use a clear, in focus image, so potential buyers can clearly see the state of the item</li>
            <li>Correctly represent and describe your product</li>
        </ul>
    </div>
</div>
    

bookspot/app/views/pages/help.html.erb
<div class="container">
    <div class="row hero">
        <h1>Welcome to Bookspot Help</h1>
        <h4>Links below to help you have your best Bookspot experience!</h4>
    </div>

        <div="u-full-width">
            <%= link_to "Effective Listing Guide", guide_path, class: "button" %>
            <%= link_to "Sitemap", sitemap_path, class: "button" %>
            <%= link_to "App Documentation", "README.pdf" , class: "button" %>
        </div>
</div>

bookspot/app/views/pages/home.html.erb
<div class="container">
    <div class="row hero">
        <h1>Welcome to Bookspot</h1>
        <h4>This is a book selling and buying platform</h4>
    </div>
</div>

bookspot/app/views/pages/sitemap.html.erb
<div class="container">
    <div class="row hero">
        <h1>Welcome to Bookspot Help</h1>
        <h4>Sitemap</h4>
    </div>
    <br>
    <br>
    <div class="one-column">
        <%= image_tag "sitemap.jpg", alt: "Sitemap", height: 370, width: 960 %>
    </div>
</div>

bookspot/app/views/search/_form.html.erb
<%= search_form_for(@query, url: search_path, method: :get) do |f| %>
    <%= f.search_field :title_i_cont_any, 
    placeholder: "Search..." %>
    <%= f.submit "Search!", class: "button" %>
<% end %>

bookspot/app/views/search/index.html.erb
<div class="container">
  <div class="row">
    <h1><%= pluralize(@listings.count, "Result") %></h1>
    <%= render 'search/form' %>

    <div>
        <table class="u-full-width">
            <thead>
                <tr>
                <th><%= sort_link(@query, :title, "Title", default_order: :asc) %></th>
                </tr>
            </thead>

            <tbody>
                  <% @listings.each do |listing| %>
                <tr>
                  <td><%= link_to listing.title, listing %></td>
                </tr>
                    <% end %>
            </tbody>
        </table>
    </div>

bookspot/app/views/shared/_nav.html.erb
<div class="container">
  <div class="row">
    <ul class="u-pull-left">
      <li><%= link_to "🏡", root_path, class: "button" %></li>
      <li><%= link_to "Listings", listings_path, class: "button"  %></li>
      <li><%= link_to "Bought Items", orders_bought_path, class: "button" %></li>
      <li><%= link_to "Sold Items", orders_sold_path, class: "button" %></li>
      <li><%= render 'search/form' %></li>
      <li><%= link_to "Help", help_path, class: "button" %></li>
    </ul>
    <ul class="u-pull-right">
    <% if account_signed_in? %>
      <li><%= link_to "Sign out", destroy_account_session_path, method: :delete, class: "button button-primary" %></li>
    <% else %>
      <li><%= link_to "Sign up", new_account_registration_path, class: "button button-primary" %></li>
    <%= link_to "Sign in", new_account_session_path, class: "button button-primary" %>
    <% end %>
    </ul>
    <div class="u-cf"></div>
</div>